### ISSUE TITLE
How about using interrupts instead of a loop? 

### ISSUE THREAD

**Issue by mrstebo** [leigh-hackspace/Ruby_RFID_Register#4]
It may be a huge benefit if you started using [interrupts](http://playground.arduino.cc/Code/Interrupts) instead of constantly looping. That way you can just pop in to a function when an RFID needs to be read.

Also you could set a "debounce rate" on the interrupt to combat #2

**Comment by pacharanero** [comment]
We should probably use the RPi's inbuilt GPIO and the [PiPiper](https://github.com/jwhitehorn/pi_piper) library which is event-driven and would obviate the need for both constant looping AND the Arduino!

**Comment by phyushin** [comment]
yea if you remember though - i had an issue with SPI not playing well on my
raspberry pi which was swhy i sued the arduino in the first place xD
