### ISSUE TITLE
Not clear whether you are signing IN or OUT at present

### ISSUE THREAD

**Issue by pacharanero** [leigh-hackspace/Ruby_RFID_Register#5]
red light flashes the same whether signing in or out.

perhaps we need an audio indication when signing in or out, which is different for those two states, and/or a different coloured light.

sorry I haven't contributed in terms of code yet; I'm getting closer to being able to get involved

**Comment by phyushin** [comment]
yea there is plans to get a green light for in and a red light for out - just need to figure out either : 
- how  to send the signal back to the the arduino
- how to use the GPIO instead as this will make it much easier in the long run
- mix of both (i think ill do this for the time being) where the status is read by the ruby script and lights are put on based on the return code - meaning @alexhartley  it going to have to alter that endpoint to return an  in / out flag
